name: notify-pr

on: pull_request_target

jobs:
  pr:
    runs-on: ubuntu-latest
    name: Pull Request Notification
    steps:
      - run: |
          echo "{\"text\":\"Vultr-CLI : PR https://github.com/vultr/vultr-cli/pull/${{ github.event.number }} \"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME}}
          MATTERMOST_ICON: ${{ secrets.MATTERMOST_ICON }}
